# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agmigrator < Formula
  desc "Akeyless Gateway Migrator"
  homepage "https://github.com/akeyless-community/akeyless-gateway-migrator"
  version "1.0.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/akeyless-community/akeyless-gateway-migrator/releases/download/1.0.2/akeyless-gateway-migrator_Darwin_arm64.tar.gz"
      sha256 "0633e80cdb9212432e85f31ae4ba24a5f85f18748cf9b6b964b95c82a12c81d1"

      def install
        bin.install "akeyless-gateway-migrator"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/akeyless-community/akeyless-gateway-migrator/releases/download/1.0.2/akeyless-gateway-migrator_Darwin_x86_64.tar.gz"
      sha256 "92cf21c0cbcd98dc101f962c43ade329aecf28fbba64c69d8e6947de24a3a6bc"

      def install
        bin.install "akeyless-gateway-migrator"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/akeyless-community/akeyless-gateway-migrator/releases/download/1.0.2/akeyless-gateway-migrator_Linux_arm64.tar.gz"
      sha256 "94e5e2c3e3d6338c8584520fe2e2fb404f37c6c344e56e9e8b42d7b92d699d21"

      def install
        bin.install "akeyless-gateway-migrator"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/akeyless-community/akeyless-gateway-migrator/releases/download/1.0.2/akeyless-gateway-migrator_Linux_x86_64.tar.gz"
      sha256 "8ab123e5b0b459d3472cf99a8ee29e53d5c3f757d23e704644a414f211f35602"

      def install
        bin.install "akeyless-gateway-migrator"
      end
    end
  end
end
